---
title: "Have Hurricanes Gotten More Severe"
output:
  html_document: default
  html_notebook: default
  pdf_document: default
---

```{r, message=FALSE, warning=FALSE}
source('db_conn.R')
source('hurricanes.R')
conn <- hurr_db_connect()

library(dplyr)
library(leaflet)
library(ggplot2)
library(pander)
# library(rjson) Trash
```

```{r ggplot Default Theme, echo=FALSE}
theme_set(theme_bw() + theme(
    legend.position="bottom",
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black")))
```

# Hurricanes
## Measuring Hurricane Intensity: Saffir-Simpson Hurricane Scale

```{r "SSHS Diagram"}
sshs_diagram()
```

## Have Hurricanes Become Worse
### Have Category 5 hurricanes become more common
```{sql connection=conn, output.var='cat5'}
SELECT
  season, name, wind_max_kt
FROM hurricane_summary
WHERE season > 1900 AND saffir_simpson(wind_max_kt) LIKE 'Category 5'
ORDER BY season DESC
```

```{r echo=FALSE}
names(cat5) = c("Season", "Name", "Peak Wind (Knots)")
pander(widen(cat5))
```

### Have they gotten stronger
```{sql connection=conn, output.var='hurr_by_year'}
SELECT
  season, count(name), round(AVG(wind_max_kt)::numeric, 1),        
  saffir_simpson(AVG(wind_max_kt)),
  saffir_simpson_color(AVG(wind_max_kt))
FROM hurricane_summary
WHERE season > 1900 AND wind_max_kt::int != -999
GROUP BY season
ORDER BY season
```

```{r "Hurricanes per Season", echo=FALSE}
ggplot(hurr_by_year, aes(x=season, y=count, fill=saffir_simpson)) +
  geom_bar(stat='identity') +
  scale_fill_manual(
    "Average Intensity",
    values = c("Tropical Depression" = "#5ebaff",
               "Tropical Storm" = "#00faf4",
               "Category 1" = "#ffffcc")
  ) +
  labs(
    title="Number of Hurricanes per Season",
    x="Year",
    y="Number"
  )
```

## 1900 Galveston Hurricane
The 1900 hurricane that hit Galveston, Texas was the deadliest hurricane in American history.

(Write more later)

```{sql connection=conn, output.var='galv1900'}
WITH galv1900 AS (SELECT * FROM hurricane_summary
WHERE season::int = 1900
AND st_intersects(path, (SELECT geom FROM us_states WHERE name LIKE 'Texas')))
SELECT
    (jsonb_array_elements(st_asgeojson(path)::jsonb->'coordinates')->>0)::float AS lon,
    (jsonb_array_elements(st_asgeojson(path)::jsonb->'coordinates')->>1)::float AS lat
FROM galv1900
```

### Path
```{r}
# See: https://stackoverflow.com/questions/42989040/how-to-troubleshoot-missing-osm-tiles-in-leaflet-html-widget
m <- leaflet()
m <- addProviderTiles(m, providers$Esri.WorldImagery, group = "Esri")
for (i in 1:nrow(galv1900)) {
  m <- addCircleMarkers(m, lng=galv1900[i, 1], lat=galv1900[i, 2])
}
m
```

